language: python
python:
  - 3.8.5

before_install:
  - pip install pycodestyle

install:
  - pip install pyenv
  - pip install -r requirements.txt

script:
  - pytest
  - coverage run --source="src/" -m pytest
  - pycodestyle src/ --ignore=E755, E501, E402
